version: '3'
services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx
    volumes:
     - ${NGINX_TEMPLATE_PATH}:/etc/nginx/conf.d/mysite.template
     - ${ROUTE_EDITOR_DATA}:${ROUTE_EDITOR_DATA_TARGET}/route_edit:ro
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=${NGINX_HOST}
     - NGINX_PORT=80
     - JENKINS_PORT=${JENKINS_PORT}
     - GHOST_PORT=${GHOST_PORT}
     - KML_UPLOAD_PORT=${KML_UPLOAD_PORT}
     - ROUTE_EDITOR_DATA_TARGET=${ROUTE_EDITOR_DATA_TARGET}
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  jenkins:
    container_name: jenkins
    user: ${JENKINS_UID}
    image: jenkins/jenkins:lts
    volumes:
      - ${JENKINS_SHARED_FOLDER}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"

  kml_upload:
    container_name: kml_upload
    user: ${KML_UPLOAD_UID}
    build: maps/kml_upload
    volumes:
      - ${KML_UPLOAD_SHARED_FOLDER}:${KML_UPLOAD_TARGET_PATH}:rw
    environment:
     - PORT=${KML_UPLOAD_PORT}
     - UPLOAD_PATH=${KML_UPLOAD_TARGET_PATH}/route.kml

  ghost:
    container_name: ghost
    user: ${GHOST_UID}
    image: ghost
    volumes:
      - ${GHOST_SHARED_FOLDER}:/var/lib/ghost/content
    environment:
      - url=${GHOST_URL}