version: '3'
services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx
    user: ${NGINX_UID}
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - "kml_upload"
      - "ghost"
      - "isso"
    volumes:
     - ${NGINX_TEMPLATE_PATH}:/etc/nginx/conf.d/mysite.template
     - ${NGINX_HTPASSWD_PATH}:/etc/nginx/htpasswd/.htpasswd:ro
     - ${NGINX_DH_PARAM_PATH}/:/etc/nginx/dhparam/dhparam-2048.pem:ro
     - ${LETS_ENCRYPT_FULLCHAIN_PATH}/live/${BLOG_HOST}/fullchain.pem:/etc/letsencrypt/live/${BLOG_HOST}/:ro
     - ${LETS_ENCRYPT_PRIVKEY_PATH}/live/${BLOG_HOST}/privkey.pem:/etc/letsencrypt/live/${BLOG_HOST}/:ro
     - ${ROUTE_EDIT_DATA}:/home/share/route_edit:ro
     - ${STATIC_DATA_PATH}:/home/share/static:ro
     - ${PHOTO_GALLERIES_PATH}:/home/share/photos_galleries:ro
    environment:
     - NGINX_HOST=${BLOG_HOST}
     - KML_UPLOAD_PORT=${KML_UPLOAD_PORT}
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  kml_upload:
    container_name: kml_upload
    build: maps/kml_upload
    user: ${KML_UPLOAD_UID}
    volumes:
      - ${KML_UPLOAD_DATA}:/home/share/upload/:rw
    environment:
     - PORT=${KML_UPLOAD_PORT}
     - UPLOAD_PATH=/home/share/upload/route.kml

  ghost:
    container_name: ghost
    image: ghost
    user: ${GHOST_UID}
    volumes:
      - ${GHOST_DATA}:/var/lib/ghost/content
    environment:
      - url=${GHOST_URL}

  isso:
    container_name: isso
    image: wonderfall/isso
    volumes:
      - ${ISSO_CONFIG_FOLDER}:/config
      - ${ISSO_DB_FOLDER}:/db
    environment:
      - UID=${ISSO_UID}
      - GID=${ISSO_GID}