version: '3'
services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx
    volumes:
     - ./reverse_proxy/reverse_proxy.template:/etc/nginx/conf.d/mysite.template
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=${NGINX_HOST}
     - NGINX_PORT=80
     - JENKINS_PORT=${JENKINS_PORT}
     - KML_UPLOAD_PORT=${KML_UPLOAD_PORT}
     - ROUTE_EDITOR_DATA=${ROUTE_EDITOR_DATA}
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "${JENKINS_PORT}:8080"
    volumes:
      - ${JENKINS_SHARED_FOLDER}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  kml_upload:
    container_name: kml_upload
    build: maps/kml_upload
    ports:
     - "${KML_UPLOAD_PORT}:8080"

  ghost:
    container_name: ghost
    volumes:
      - ${GHOST_SHARED_FOLDER}:/var/lib/ghost:content
    ports:
      - ${GHOST_PORT}:2368
    environment:
      - url:${GHOST_URL}