version: '3'
services:
  reverse_proxy:
    container_name: reverse_proxy
    image: nginx
    volumes:
     - ${NGINX_TEMPLATE_PATH}:/etc/nginx/conf.d/mysite.template
     - ${NGINX_PASSWORD_PATH}:/etc/nginx/htpasswd:ro
     - ${ROUTE_EDITOR_DATA_HOST}:${ROUTE_EDITOR_DATA_CONTAINER}/route_edit:ro
     - ${STATIC_COMMON_DATA_HOST}:${STATIC_COMMON_DATA_CONTAINER}:ro
     - ${PHOTO_GALLERIES_DATA_HOST}:${PHOTO_GALLERIES_DATA_CONTAINER}:ro
     - ${DH_PARAM_DATA_HOST}/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
     - ${LETS_ENCRYPT_DATA_HOST}/live/${BLOG_HOST}/fullchain.pem:/etc/letsencrypt/live/${BLOG_HOST}/fullchain.pem
     - ${LETS_ENCRYPT_DATA_HOST}/live/${BLOG_HOST}/privkey.pem:/etc/letsencrypt/live/${BLOG_HOST}/privkey.pem
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - "kml_upload"
      - "ghost"
      - "isso"
    environment:
     - NGINX_HOST=${NGINX_HOST}
     - NGINX_PORT=80
     - GHOST_PORT=${GHOST_PORT}
     - KML_UPLOAD_PORT=${KML_UPLOAD_PORT}
     - ISSO_PORT=${ISSO_PORT}
     - ROUTE_EDITOR_DATA_CONTAINER=${ROUTE_EDITOR_DATA_CONTAINER}
     - PHOTO_GALLERIES_DATA_CONTAINER=${PHOTO_GALLERIES_DATA_CONTAINER}
     - STATIC_COMMON_DATA_CONTAINER=${STATIC_COMMON_DATA_CONTAINER}
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  kml_upload:
    container_name: kml_upload
    user: ${KML_UPLOAD_UID}
    build: maps/kml_upload
    volumes:
      - ${KML_UPLOAD_DATA_HOST}:${KML_UPLOAD_DATA_CONTAINER}:rw
    environment:
     - PORT=${KML_UPLOAD_PORT}
     - UPLOAD_PATH=${KML_UPLOAD_DATA_CONTAINER}/route.kml

  ghost:
    container_name: ghost
    user: ${GHOST_UID}
    image: ghost
    volumes:
      - ${GHOST_DATA_HOST}:/var/lib/ghost/content
    environment:
      - url=${GHOST_URL}

  isso:
    container_name: isso
    image: wonderfall/isso
    volumes:
      - ${ISSO_CONFIG_FOLDER_HOST}:${ISSO_CONFIG_FOLDER_CONTAINER}
      - ${ISSO_DB_FOLDER_HOST}:${ISSO_DB_FOLDER_CONTAINER}
    environment:
      - UID=${ISSO_UID}
      - GID=${ISSO_GID}